In [1]:
import datetime as dt
import time as tm

In [3]:
tm.time()

1642794957.2892046

In [6]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2022, 1, 21, 19, 56, 31, 18823)

In [8]:
delta =dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [11]:
today=dt.date.today()
today

datetime.date(2022, 1, 21)

# OOP in python

In [12]:
class person:
    department ='school of information'
    
    def set_nam(self,new_name):
        self.name=new_name
    def set_location(self,new_location):
        self.location=new_location
    def get_name(self):
        return self.name
    def get_location(self):
        return self.location
    

# Map()  in python is like for loop

In [16]:
store1=[10,20,30,40,50]
store2=[30,85,10,10,30]
cheapest= map(min,store1,store2)
list(cheapest)

[10, 20, 10, 10, 30]

# numpy

In [1]:
import numpy as np
import math

# Array creation

In [5]:
#array are displ;ayed as a list of list 
a= np.array([1,2,3])
print (a)
# we can print the dimension of the array
print(a.ndim)

[1 2 3]
1


In [14]:
#if we pass in a list of list in numpy array, we crate amutlti dimesntional array 
b=np.array([[1,2,3],[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [1 2 3]
 [4 5 6]]


(3, 3)

In [16]:
# check the typr of items 
a.dtype

dtype('int64')

In [18]:
# float one
c= np.array([[1,2,3],[0.1,2,3]])
c

array([[1. , 2. , 3. ],
       [0.1, 2. , 3. ]])

In [22]:
# fill with zeors
d=np.zeros((2,3))
print(d)
e=np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
np.random.rand(2,3)
# create ranodm


array([[0.89451667, 0.73297228, 0.07606854],
       [0.27833434, 0.02294123, 0.5146201 ]])

In [30]:
# create a sequnce of number in array
f=np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [32]:
# sequnce of float
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Array operations

In [34]:
# arithmetic operators on array apply elemtwise
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a+b

array([3, 5, 7, 9])

In [36]:
a-b

array([-1, -1, -1, -1])

In [39]:
a*b
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [42]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B
# @ is dot produnt
A@B



array([[5, 4],
       [3, 4]])

In [44]:
# upcasting 
array1=np.array([[1,2,3],[47,5,6]])
array2=np.array([[1.2,2,3],[47,5,6]])

print(array1+array2)

[[ 2.2  4.   6. ]
 [94.  10.  12. ]]


In [45]:
from PIL import Image
from IPython.display import display



# indexing slicing and iterating

# indexing


In [47]:
a=np.array([1,3,4,5])
a[2]

4

In [57]:
a=np.array([[1,2],[1,2],[1,58]])
a[1,1]

2

In [58]:
np.array([a[0,0],a[1,1],a[2,1]])


array([ 1,  2, 58])

In [53]:
print(a[[0,1,2],[0,1,1]])

[1 2 2]


# boolean indexing

In [59]:
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [61]:
print(a[a>5])

[58]


# slicing


In [63]:
# to slice used :
a= np.array([1,2,3,4,5,6])
print(a[:3])

[1 2 3]


In [65]:
print(a[2:4])

[3 4]


In [67]:
# muti demison
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
a[:2,1:3]
# first is for slecte row, second is for select collumn

array([[2, 3],
       [6, 7]])

In [71]:
# it is importance to realize trhat aslice of an array is aview inbto the same data, this is called oassubng by reference. so modifyng the sub array will consequently modifu the original array

In [74]:
sub_array=a[:2,1:3]
sub_array[0,0]=50
a

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Trying numpy with datasets

In [77]:
wines =np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [79]:
print("one interger 0 for slicing: ",wines[:,0])

one interger 0 for slicing:  [7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [82]:
print("0 to 1 for sling",wines[:,0:1])

0 to 1 for sling [[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [84]:
wines[:,0:3]

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]])

In [87]:
wines[:,[0,2,4]]

array([[7.4  , 0.   , 0.076],
       [7.8  , 0.   , 0.098],
       [7.8  , 0.04 , 0.092],
       ...,
       [6.3  , 0.13 , 0.076],
       [5.9  , 0.12 , 0.075],
       [6.   , 0.47 , 0.067]])

In [89]:
wines[:,-1].mean()

5.6360225140712945

In [119]:
graduate_admission=np.genfromtxt('Admission_Predict-Copy1.csv',dtype=None,delimiter=",",skip_header=1,names=('Id',"GRE_Dcore","TOEFL Score","University Rating","Sop","LOR","cGPA","reasch","change_of_admit"))
graduate_admission


array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [108]:
graduate_admission.shape

(400,)

In [109]:
graduate_admission["cGPA"][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [111]:
graduate_admission["cGPA"]=(graduate_admission["cGPA"]*4/10)
graduate_admission["cGPA"]

array([1.544 , 1.4192, 1.28  , 1.3872, 1.3136, 1.4944, 1.312 , 1.264 ,
       1.28  , 1.376 , 1.344 , 1.44  , 1.456 , 1.28  , 1.312 , 1.328 ,
       1.392 , 1.28  , 1.408 , 1.36  , 1.264 , 1.344 , 1.52  , 1.552 ,
       1.568 , 1.536 , 1.408 , 1.2   , 1.152 , 1.168 , 1.296 , 1.328 ,
       1.504 , 1.536 , 1.568 , 1.472 , 1.344 , 1.248 , 1.2   , 1.232 ,
       1.28  , 1.312 , 1.36  , 1.456 , 1.504 , 1.456 , 1.488 , 1.552 ,
       1.416 , 1.344 , 1.328 , 1.264 , 1.28  , 1.296 , 1.28  , 1.232 ,
       1.184 , 1.216 , 1.088 , 1.328 , 1.296 , 1.312 , 1.312 , 1.36  ,
       1.392 , 1.4272, 1.4432, 1.3824, 1.4752, 1.4656, 1.5424, 1.5616,
       1.512 , 1.4464, 1.424 , 1.3696, 1.3952, 1.3152, 1.2064, 1.1776,
       1.2832, 1.52  , 1.4752, 1.4976, 1.512 , 1.3856, 1.3472, 1.3248,
       1.3024, 1.4016, 1.2672, 1.2256, 1.2848, 1.2608, 1.2256, 1.2544,
       1.28  , 1.4336, 1.4784, 1.4208, 1.3536, 1.2992, 1.32  , 1.3552,
       1.448 , 1.4048, 1.4688, 1.5136, 1.5008, 1.3824, 1.3568, 1.3888,
      

In [114]:
len(graduate_admission[graduate_admission["reasch"]==1])

219

In [130]:
print(graduate_admission[graduate_admission["change_of_admit"]>0.8]["GRE_Dcore"].mean())

328.7350427350427
